version: 0.2

phases:
  build:
    commands:
    - echo "This is build phase... Zipping my lambda function"
    - zip -r deployment_package.zip index.js
  post_build:
    commands:
    - echo "Deploying to the Lambda"
    - aws lambda update-function-code --function-name  lambda-manual --zip-file fileb://deployment_package.zip
artifacts:
  type: zip
  paths:
    - '*'
