version: 0.2

phases:
  pre_build:
    commnads:
  #  -  yum update -y
   # -  yum install unzip -y
  build:
    commands:
    - echo "This is build phase... Zipping my lambda functionn"
    - aws s3 cp s3://test-node-js-bucket-ces/lambda-s3/ . --recursive
    - zip -r deployment_package.zip *
  post_build:
    commands:
    - echo "Deploying to the Lambdaa"
    - aws lambda update-function-code --function-name  lambda-manual --zip-file fileb://deployment_package.zip
   # - unzip -t *
artifacts:
   type: zip
   paths:
  # files:
     - '*'
